#!/bin/bash

BASEDIR=$PWD
COUNTER=0

# Abort immediately on errors
set -e

function git_fetch {
	echo ''
	echo --- $1
	cd $1
	let COUNTER=COUNTER+1
	# Fetch tags only from primary upstream repo
	# The follwing command may fail. This is ok.
	set +e
	git fetch --tags
	set -e
	# Fetch everything from all repositories.
	git fetch --all		
	if [ -e .git/svn/refs/remotes ]; then
		echo Fetching SVN commits...
		git svn fetch --log-window-size=10000
		# The follwing command may fail. This is ok.
		set +e
		#echo Trying a 'git svn rebase -l'
		git svn rebase -l 2> /dev/null
		set -e
	fi
}

if [ -z "$1" ]; then
    COMMAND="fetch"
    ARGS=""
else 
    COMMAND="$1"
    ARGS="${*:2}"
fi    

case $COMMAND in
fetch)
	for gitdir in $( find $BASEDIR -maxdepth 1 -name '*.git' -type d ); do
    	git_fetch $gitdir
	done
	;;
*)
	for gitdir in $( find $BASEDIR -maxdepth 1 -name '*.git' -type d ); do
		echo ''
		echo --- $gitdir
    	cd $gitdir
  		let COUNTER=COUNTER+1
    	#echo Executing: git $COMMAND $ARGS
    	git $COMMAND $ARGS
	done
	;;
esac

echo 
echo Success: $COUNTER Git directories processed with "git $COMMAND $ARGS"

